name: Deploy package

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-deploy-jdk-package
          ref: v1.0.4
          token: '${{ secrets.ACTIONS_FETCH_TOKEN }}'
          path: .github/actions/action-deploy-jdk-package

      - name: Deploy package
        uses: ./.github/actions/action-deploy-jdk-package
        with:
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}